### ISSUE TITLE
Question: how do you stop the interval from running?

### ISSUE THREAD

**Issue by ultrarunner** [unimonkiez/self-adjusting-interval#1]
First of all, thank you very much for taking the time to put this helper out there. I encountered the setInterval() and setTimeout() issues on a project where there is a timer running and it was slowly going out of sync.
I am using the library in an anguar 5+, typescript project and the only way I could make the interval from running was by moving the "stop" variable out of the interval and setting it to true whenever a user presses a "stop" button. I am pretty sure I must be missing something. Thank you.

**Comment by unimonkiez** [comment]
Hey! Thanks for your feedback. 
This reminds me I need to add support for typescript definition...

Any, the function returns another function which is the stop method.  
So basically :
```js
import setSelfAdjustInterval from 'self-adjusting-interval';
const stopInterval = setSelfAdjustInterval(...);
stopInterval();
```
